
apiVersion: v1
kind: ServiceAccount
metadata:
  name: re-commerce-enterprise
  namespace: re-commerce-enterprise
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: re-commerce-enterprise
  namespace: re-commerce-enterprise
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: re-commerce-enterprise
  namespace: re-commerce-enterprise
subjects:
- kind: ServiceAccount
  name: re-commerce-enterprise
  namespace: re-commerce-enterprise
roleRef:
  kind: Role
  name: re-commerce-enterprise
  apiGroup: rbac.authorization.k8s.io
